//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpchDestroyer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpchDestroyer.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_common_error {
            get {
                return ResourceManager.GetString("error.common.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please open a folder! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_common_plzfolder {
            get {
                return ResourceManager.GetString("error.common.plzfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is not a folder! Please open a folder! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_open_notfolder {
            get {
                return ResourceManager.GetString("error.open.notfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destroy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_common_destroy {
            get {
                return ResourceManager.GetString("info.common.destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destroy ipch files were finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_destroy_done {
            get {
                return ResourceManager.GetString("info.destroy.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destroy ipch files were failed! :
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_destroy_fail {
            get {
                return ResourceManager.GetString("info.destroy.fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destroy all ipch files in
        ///&quot;{0}&quot;.
        ///Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_execute_check {
            get {
                return ResourceManager.GetString("info.execute.check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DESTROY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item_btndestroy {
            get {
                return ResourceManager.GetString("item.btndestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item_tbltarget {
            get {
                return ResourceManager.GetString("item.tbltarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ipch Destroyer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item_windowtitle {
            get {
                return ResourceManager.GetString("item.windowtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select destroy folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string text_open_pickfolder {
            get {
                return ResourceManager.GetString("text.open.pickfolder", resourceCulture);
            }
        }
    }
}
